[package]
name = "prism-os"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
poslib = { path = "poslib" }
lazy_static = "1.4.0"
embedded-graphics = "0.7.1"
bitmap-font = "0.2.2"
tinytga = "0.4.1"
fixed-queue = "0.5.1"
